### ISSUE TITLE
Waiting for payload signal!

### ISSUE THREAD

**Issue by kuroshZ** [Gremsy/PayloadSdk#13]
### Problem Description:
PayloadSDK cannot establish a connection with the camera bot over UART/USB and UDP. 

### Error Messages
USB:
![usb](https://github.com/Gremsy/PayloadSdk/assets/157474691/52510c5e-32e0-402a-8bcb-c85de1e69426)

UDP:
![udp](https://github.com/Gremsy/PayloadSdk/assets/157474691/9d11e425-3c6e-46b9-aaa4-50b3f4fd664b)

### Hardware Setup:
LAN wire connection from the laptop and camera to the router. 
USB connection from the laptop to the camera using a CP2102 Adapter as described in the manual. 

#### Operating System:
NAME="Fedora Linux"
VERSION="39 (Workstation Edition)"
ID=fedora
VERSION_ID=39

### Firmware Information 
Gremsy ZIO
ZIO Firmware Version: gremsyZio_v781_Official
Gremsy Payload: Gremsy Zio Firmware v780 Official 
also tried with Gremsy Zio Firmware v781 Official

#### payload_setup.txt
This file is copied to the MicroSD Card of the camera. 

/*PAYLOAD CONFIGURATION*/ 
ZIO_ADDR = 192.168.0.190
NETMASK = 255.255.255.0
GATEWAY = 192.168.0.1

####  PayloadSdk Build
git clone -b develop --recurse-submodules https://github.com/Gremsy/PayloadSdk.git

cd PayloadSdk/libs/gSDK/
git checkout gSDK_V3_alpha
git pull origin gSDK_V3_alpha

Change IP address in case of UDP and change the CONTROL_METHOD in payloadsdk.h accordingly. 

cd PayloadSdk 
mkdir build && cd build  
cmake ..  
make -j6  

### Related Questions:
After copying the payload_setup.txt file to the SD Card, you can ping the payload which indicates that the setup worked. However, when you turn off the camera and turn it back on, the ping command returns the error message "Destination Host Unreachable".
If you check the SD card now, you will see that the payload_setup file has been deleted!
I am wondering if I am missing something here or if there is an actual bug in PayloadSdk that prevents the connection.

**Comment by lamGremsy** [comment]
Hi kuroshZ,

Please check Zio SoM Firmware in the following way:
- Plug the HDMI from Zio into the monitor.
- Change OSD mode to Debug
- See the Zio SoM Firmware on the screen in the first row

**Comment by kuroshZ** [comment]
How can I change it to the OSD debug mode without a px4?

**Comment by lamGremsy** [comment]
Can't change it to the OSD debug mode without a px4 or without PayloadSDK
Please use GremsyFlashTool to upgrade SoM firmware version 2.0.1.4 build03042024
Tutorial link: https://docs.gremsy.com/payloads/zio-manual-v2/upgrade-firmware/upgrade-som-firmware

**Comment by kuroshZ** [comment]
What is the default port of the UDP connection?

**Comment by kuroshZ** [comment]
I used  the port 14566 in QGroundControll for the UDP connection and set the px4 parameters as described in the manual but I can see no Gremsy window!
