### ISSUE TITLE
PAYLOAD_CAMERA_GIMBAL_MODE wrongly numbered

### ISSUE THREAD

**Issue by thijs83** [Gremsy/PayloadSdk#18]
Hi Gremsy,

In the payloadsdk.h, I think the modes are wrongly numbered. PAYLOAD_CAMERA_GIMBAL_MODE_OFF is correct, PAYLOAD_CAMERA_GIMBAL_MODE_FOLLOW behaves as the lock command and the PAYLOAD_CAMERA_GIMBAL_MODE_LOCK behaves as the follow command.

So I would say that those two defines should be switched.

**Comment by penguin-dang** [comment]
Hi thijs83,

We've already updated the latest version of Payload SDK in develop branch.
There are some changes to cmake build, please check the README.md file for details. 

Thank you for your contribution.
