### ISSUE TITLE
Photo Mode: Time lapse trigger

### ISSUE THREAD

**Issue by thijs83** [Gremsy/PayloadSdk#22]
Hi Gremsy,

Is there already the possibility to change the Photo Mode to Time Lapse and then trigger the recording and a stop trigger? 

I can use it through QGroundControl, but haven't found a way to do it through this SDK

**Comment by penguin-dang** [comment]
Hi Thijs83,

Thank you for your contributions. We've already updated an example for Time Lapse Photography.
You can pull develop branch and check it.

If you have any additional features to suggest, please let us know.
