### ISSUE TITLE
input type to regPayloadStatusChanged( ) and others

### ISSUE THREAD

**Issue by thijs83** [Gremsy/PayloadSdk#23]
Hi Gremsy,

Is it possible to change the input type of the 'regPayloadStatusChanged( )' callback function? 
Currently it takes in a
`void (*)(int,double)`
But this causes a problem if you want to use it inside a class and register a member function:
`void (A::*)(int,double)`

To solve this problem:
`typedef void (*payload_status_callback_t)(int event, double* param);`
`typedef void (*payload_param_callback_t)(int event, char* param_char, double* param_double);`
`typedef void (*payload_streamInfo_callback_t)(int event, char* param_char, double* param_double);`
could be changed to:
`typedef std::function<void(int event, double* param)> payload_status_callback_t;`
`typedef std::function<void(int event, char* param_char, double* param_double)> payload_param_callback_t;`
`typedef std::function<void(int event, char* param_char, double* param_double)> payload_streamInfo_callback_t;`
Now the 3 register functions can take in both global and class member functions.

**Comment by penguin-dang** [comment]
Hi Thijs83,

I greatly appreciate your contributions. I've already moved all of the callback_functions to class. From now on, we can register callback_funtions in both global and class member functions.

I provide you with the code for the case of using class member functions.

Thank you and I hope to get more distributions from you as well.

![Screenshot from 2024-07-01 15-20-23](https://github.com/Gremsy/PayloadSdk/assets/86837525/c985f266-90bb-4b72-bdde-2b1f60359470)
