### ISSUE TITLE
No zoom update on example get_payload_status

### ISSUE THREAD

**Issue by jorgeffonte** [Gremsy/PayloadSdk#28]
I've successfully installed the Payload SDK, and I'm able to connect my ZIO payload through UDP (Ethernet connection). I can run some example codes to move the gimbal, zoom in, etc.

The issue arises when I run the get_payload_status example in one terminal and eo_set_camera_zoom_focus in another. I can confirm that the zoom is actually changing by visualizing the RTSP stream via GStreamer, but in the get_payload_status terminal, there are only updates for the gimbal attitude, but none for the gimbal zoom.

I'm printing the event and param values at the start of the onPayloadStatusChanged function, but the only event I receive is PAYLOAD_GB_ATTITUDE.
```
void onPayloadStatusChanged(int event, double* param){
	
	switch(event){
	case PAYLOAD_GB_ATTITUDE:{
		// param[0]: pitch
		// param[1]: roll
		// param[2]: yaw

		printf("Pich: %.2f - Roll: %.2f - Yaw: %.2f\n", param[0], param[1], param[2]);
		break;
	}
	case PAYLOAD_PARAMS:{
		// param[0]: param index
		// param[1]: value
		if(param[0] == PARAM_EO_ZOOM_LEVEL){
			printf("Payload EO_ZOOM_LEVEL: %.2f \n", param[1]);
		}
		else if(param[0] == PARAM_IR_ZOOM_LEVEL){
			printf("Payload IR_ZOOM_LEVEL: %.2f \n", param[1]);
		}
```

**Comment by penguin-dang** [comment]
Which PayloadSDK branch and ZIO Software version are you using?
Did you setParamRate for PARAM_EO_ZOOM_LEVEL? 
"my_payload->setParamRate(PARAM_EO_ZOOM_LEVEL, 1000);"
